### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by Xee1** [coolsquid/ConflictHelper#2]
Hi @coolsquid , I've get this error, and the mod doesn't work.
 [18:00:11] [main/ERROR] [FML]: Coremod ConflictHelperPlugin: Unable to class load the plugin coolsquid.conflicthelper.ConflictHelperPlugin
java.lang.ClassNotFoundException: coolsquid.conflicthelper.ConflictHelperPlugin
at java.net.URLClassLoader$1.run(URLClassLoader.java:366) ~[?:1.7.0_76]
at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[?:1.7.0_76]
at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_76]
at java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[?:1.7.0_76]
at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117) ~[launchwrapper-1.11.jar:?]
at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_76]
at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_76]
at java.lang.Class.forName0(Native Method) ~[?:1.7.0_76]
at java.lang.Class.forName(Class.java:274) ~[?:1.7.0_76]
at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:417) [forge-1.7.10-10.13.3.1395-1710ls-universal.jar:?]
at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:346) [forge-1.7.10-10.13.3.1395-1710ls-universal.jar:?]
at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:214) [forge-1.7.10-10.13.3.1395-1710ls-universal.jar:?]
at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90) [forge-1.7.10-10.13.3.1395-1710ls-universal.jar:?]
at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67) [forge-1.7.10-10.13.3.1395-1710ls-universal.jar:?]
at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34) [forge-1.7.10-10.13.3.1395-1710ls-universal.jar:?]
at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126) [forge-1.7.10-10.13.3.1395-1710ls-universal.jar:?]
at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.11.jar:?]
at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_76]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_76]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_76]
at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_76]
at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:273) [NewLaunch.jar:?]
at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:363) [NewLaunch.jar:?]
at org.multimc.EntryPoint.listen(EntryPoint.java:165) [NewLaunch.jar:?]
at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]

**Comment by coolsquid** [comment]
I see the issue. Building a new version now.

**Comment by Xee1** [comment]
Thanks!
